import type { Donor } from './types';

export const mockDonors: Donor[] = [
  {
    id: '101',
    name: 'Eleanor Vance',
    phone: '555-0101',
    email: 'eleanor.v@example.com',
    status: 'pending',
    lastInteraction: null,
    totalDonations: 1500,
    lastDonationDate: new Date('2023-11-15'),
  },
  {
    id: '102',
    name: 'Marcus Thorne',
    phone: '555-0102',
    email: 'marcus.t@example.com',
    status: 'pending',
    lastInteraction: null,
    totalDonations: 750,
    lastDonationDate: new Date('2023-10-20'),
  },
  {
    id: '103',
    name: 'Seraphina Moon',
    phone: '555-0103',
    email: 'seraphina.m@example.com',
    status: 'completed',
    lastInteraction: {
      id: 'int-001',
      outcome: 'completed',
      notes: 'Had a great conversation, she is happy to increase her monthly donation.',
      loggedAt: new Date('2024-05-10'),
      loggedBy: 'Admin',
    },
    totalDonations: 3200,
    lastDonationDate: new Date('2024-01-05'),
  },
  {
    id: '104',
    name: 'Julian Hayes',
    phone: '555-0104',
    email: 'julian.h@example.com',
    status: 'pending',
    lastInteraction: null,
    totalDonations: 250,
    lastDonationDate: new Date('2023-08-01'),
  },
  {
    id: '105',
    name: 'Aria Petrova',
    phone: '555-0105',
    email: 'aria.p@example.com',
    status: 'skipped',
    lastInteraction: null,
    totalDonations: 5000,
    lastDonationDate: new Date('2023-12-25'),
  },
  {
    id: '106',
    name: 'Leo Maxwell',
    phone: '555-0106',
    email: 'leo.m@example.com',
    status: 'pending',
    lastInteraction: null,
    totalDonations: 100,
    lastDonationDate: new Date('2024-02-18'),
  },
  {
    id: '107',
    name: 'Isla Chen',
    phone: '555-0107',
    email: 'isla.c@example.com',
    status: 'completed',
    lastInteraction: {
      id: 'int-002',
      outcome: 'left-vm',
      notes: 'Left a voicemail thanking her for her continued support and mentioning the new campaign.',
      loggedAt: new Date('2024-05-09'),
      loggedBy: 'Admin',
    },
    totalDonations: 950,
    lastDonationDate: new Date('2023-09-30'),
  },
];
